;;; commitments.scm — Commitment query index

(use-modules (srfi srfi-1) (goblins utils hashmap))

(define (build-commitment-index commitments)
  (let ((items (hashmap)) (by-spec (hashmap)) (by-action (hashmap))
        (by-agent (hashmap)) (by-plan (hashmap)) (by-process (hashmap))
        (by-intent (hashmap)))
    (for-each
      (lambda (c)
        (let ((id (commitment-id c)))
          (set! items (hashmap-set items id c))
          (when (commitment-resource-conforms-to c)
            (set! by-spec (hashmap-set by-spec (commitment-resource-conforms-to c)
                            (cons id (hashmap-ref by-spec (commitment-resource-conforms-to c) '())))))
          (set! by-action (hashmap-set by-action (commitment-action c)
                            (cons id (hashmap-ref by-action (commitment-action c) '()))))
          (when (commitment-provider c)
            (set! by-agent (hashmap-set by-agent (commitment-provider c)
                            (cons id (hashmap-ref by-agent (commitment-provider c) '())))))
          (when (commitment-receiver c)
            (set! by-agent (hashmap-set by-agent (commitment-receiver c)
                            (cons id (hashmap-ref by-agent (commitment-receiver c) '())))))
          (when (commitment-planned-within c)
            (set! by-plan (hashmap-set by-plan (commitment-planned-within c)
                            (cons id (hashmap-ref by-plan (commitment-planned-within c) '())))))
          (when (commitment-input-of c)
            (set! by-process (hashmap-set by-process (commitment-input-of c)
                              (cons id (hashmap-ref by-process (commitment-input-of c) '())))))
          (when (commitment-output-of c)
            (set! by-process (hashmap-set by-process (commitment-output-of c)
                              (cons id (hashmap-ref by-process (commitment-output-of c) '())))))
          (when (commitment-satisfies c)
            (set! by-intent (hashmap-set by-intent (commitment-satisfies c)
                              (cons id (hashmap-ref by-intent (commitment-satisfies c) '())))))))
      commitments)
    `((items . ,items) (by-spec . ,by-spec) (by-action . ,by-action)
      (by-agent . ,by-agent) (by-plan . ,by-plan) (by-process . ,by-process)
      (by-intent . ,by-intent))))

(define (query-commitments-by-spec idx id)
  (filter-map (lambda (i) (hashmap-ref (assq-ref idx 'items) i #f))
              (hashmap-ref (assq-ref idx 'by-spec) id '())))
(define (query-commitments-by-action idx a)
  (filter-map (lambda (i) (hashmap-ref (assq-ref idx 'items) i #f))
              (hashmap-ref (assq-ref idx 'by-action) a '())))
(define (query-commitments-by-agent idx id)
  (filter-map (lambda (i) (hashmap-ref (assq-ref idx 'items) i #f))
              (hashmap-ref (assq-ref idx 'by-agent) id '())))
(define (query-commitments-by-plan idx id)
  (filter-map (lambda (i) (hashmap-ref (assq-ref idx 'items) i #f))
              (hashmap-ref (assq-ref idx 'by-plan) id '())))
(define (query-commitments-by-process idx id)
  (filter-map (lambda (i) (hashmap-ref (assq-ref idx 'items) i #f))
              (hashmap-ref (assq-ref idx 'by-process) id '())))
(define (query-commitments-by-intent idx id)
  (filter-map (lambda (i) (hashmap-ref (assq-ref idx 'items) i #f))
              (hashmap-ref (assq-ref idx 'by-intent) id '())))
