;;; economic-events.scm — Event query index

(use-modules (srfi srfi-1) (goblins utils hashmap))

(define (build-economic-event-index events)
  (let ((items (hashmap)) (by-spec (hashmap)) (by-action (hashmap))
        (by-agent (hashmap)) (by-resource (hashmap)) (by-process (hashmap)))
    (for-each
      (lambda (e)
        (let ((id (economic-event-id e)))
          (set! items (hashmap-set items id e))
          (when (economic-event-resource-conforms-to e)
            (set! by-spec (hashmap-set by-spec (economic-event-resource-conforms-to e)
                            (cons id (hashmap-ref by-spec (economic-event-resource-conforms-to e) '())))))
          (set! by-action (hashmap-set by-action (economic-event-action e)
                            (cons id (hashmap-ref by-action (economic-event-action e) '()))))
          (when (economic-event-provider e)
            (set! by-agent (hashmap-set by-agent (economic-event-provider e)
                            (cons id (hashmap-ref by-agent (economic-event-provider e) '())))))
          (when (economic-event-receiver e)
            (set! by-agent (hashmap-set by-agent (economic-event-receiver e)
                            (cons id (hashmap-ref by-agent (economic-event-receiver e) '())))))
          (when (economic-event-resource-inventoried-as e)
            (set! by-resource (hashmap-set by-resource (economic-event-resource-inventoried-as e)
                                (cons id (hashmap-ref by-resource (economic-event-resource-inventoried-as e) '())))))
          (when (economic-event-input-of e)
            (set! by-process (hashmap-set by-process (economic-event-input-of e)
                              (cons id (hashmap-ref by-process (economic-event-input-of e) '())))))
          (when (economic-event-output-of e)
            (set! by-process (hashmap-set by-process (economic-event-output-of e)
                              (cons id (hashmap-ref by-process (economic-event-output-of e) '())))))))
      events)
    `((items . ,items) (by-spec . ,by-spec) (by-action . ,by-action)
      (by-agent . ,by-agent) (by-resource . ,by-resource) (by-process . ,by-process))))

(define (query-events-by-spec idx id)
  (filter-map (lambda (i) (hashmap-ref (assq-ref idx 'items) i #f))
              (hashmap-ref (assq-ref idx 'by-spec) id '())))
(define (query-events-by-action idx a)
  (filter-map (lambda (i) (hashmap-ref (assq-ref idx 'items) i #f))
              (hashmap-ref (assq-ref idx 'by-action) a '())))
(define (query-events-by-agent idx id)
  (filter-map (lambda (i) (hashmap-ref (assq-ref idx 'items) i #f))
              (hashmap-ref (assq-ref idx 'by-agent) id '())))
(define (query-events-by-resource idx id)
  (filter-map (lambda (i) (hashmap-ref (assq-ref idx 'items) i #f))
              (hashmap-ref (assq-ref idx 'by-resource) id '())))
(define (query-events-by-process idx id)
  (filter-map (lambda (i) (hashmap-ref (assq-ref idx 'items) i #f))
              (hashmap-ref (assq-ref idx 'by-process) id '())))
