;;; economic-resources.scm — Resource query index

(use-modules (srfi srfi-1) (goblins utils hashmap))

(define (build-economic-resource-index resources)
  (let ((items (hashmap)) (by-spec (hashmap)) (by-accountable (hashmap))
        (by-stage (hashmap)) (by-location (hashmap)))
    (for-each
      (lambda (r)
        (let ((id (economic-resource-id r)))
          (set! items (hashmap-set items id r))
          (when (economic-resource-conforms-to r)
            (set! by-spec (hashmap-set by-spec (economic-resource-conforms-to r)
                            (cons id (hashmap-ref by-spec (economic-resource-conforms-to r) '())))))
          (when (economic-resource-primary-accountable r)
            (set! by-accountable (hashmap-set by-accountable (economic-resource-primary-accountable r)
                                   (cons id (hashmap-ref by-accountable (economic-resource-primary-accountable r) '())))))
          (when (economic-resource-stage r)
            (set! by-stage (hashmap-set by-stage (economic-resource-stage r)
                            (cons id (hashmap-ref by-stage (economic-resource-stage r) '())))))
          (when (economic-resource-current-location r)
            (set! by-location (hashmap-set by-location (economic-resource-current-location r)
                                (cons id (hashmap-ref by-location (economic-resource-current-location r) '())))))))
      resources)
    `((items . ,items) (by-spec . ,by-spec) (by-accountable . ,by-accountable)
      (by-stage . ,by-stage) (by-location . ,by-location))))

(define (query-resources-by-spec idx id)
  (filter-map (lambda (i) (hashmap-ref (assq-ref idx 'items) i #f))
              (hashmap-ref (assq-ref idx 'by-spec) id '())))
(define (query-resources-by-accountable idx id)
  (filter-map (lambda (i) (hashmap-ref (assq-ref idx 'items) i #f))
              (hashmap-ref (assq-ref idx 'by-accountable) id '())))
(define (query-resources-by-stage idx id)
  (filter-map (lambda (i) (hashmap-ref (assq-ref idx 'items) i #f))
              (hashmap-ref (assq-ref idx 'by-stage) id '())))
(define (query-resources-by-location idx id)
  (filter-map (lambda (i) (hashmap-ref (assq-ref idx 'items) i #f))
              (hashmap-ref (assq-ref idx 'by-location) id '())))
